import type { EightBitReelProps } from "../../../types/eight-bit-reel";

export const DEFAULT_8BIT_PROPS: EightBitReelProps = {
  topic: "Tencent HY4 - 770B MoE Engine",
  tagBucket: "Bucket 1",
  authorHandle: "@byteswithbittu",
  crtBrand: "tencent",
  crtSubtitle: "Tencent HY4",
  audioSrc: "compositions/tencent-hy4-reel/audio_snappy/full_voice_snappy.wav",
  bgMusicSrc: "bg_music.wav",
  scenes: [
    {
      id: "scene-1",
      type: "intro-workstation",
      headline: "Tencent Dropped An AI Bombshell!",
      subheadline: "HY4 • 770B OPEN-WEIGHTS FOUNDATION MODEL",
      durationInFrames: 143,
      captions: [
        { text: "STOP SCROLLING!", fromFrame: 0, durationInFrames: 35, isHighlight: true },
        { text: "TENCENT JUST", fromFrame: 35, durationInFrames: 36, isHighlight: true },
        { text: "DROPPED THE", fromFrame: 71, durationInFrames: 36, isHighlight: false },
        { text: "AI BOMBSHELL!", fromFrame: 107, durationInFrames: 36, isHighlight: true },
      ],
    },
    {
      id: "scene-2",
      type: "editorial-card",
      tabLabel: "architecture",
      tabColor: "#8B5CF6",
      title: "770B MoE Engine",
      subtitle: "Sparse Mixture-of-Experts Router Breakdown",
      durationInFrames: 151,
      items: [
        { num: "1", title: "Expert 1 (Code)", desc: "Full-stack software engineering, refactoring & PRs", tag: "official", tagColor: "#DCFCE7" },
        { num: "2", title: "Expert 2 (Logic)", desc: "Multi-step mathematical reasoning & proofs", tag: "active", tagColor: "#FEF9C3" },
        { num: "3", title: "Expert 3 (3D Dev)", desc: "3D spatial asset generation & geometry", tag: "partner", tagColor: "#E0E7FF" },
        { num: "4", title: "Expert 4 (Math)", desc: "High-precision algorithmic compute optimization", tag: "100% ★", tagColor: "#FCE7F3" },
      ],
      footerNote: "Only 49B parameters fire per token = lightning speed.",
      emote: "lightbulb",
      captions: [
        { text: "MEET HY4:", fromFrame: 0, durationInFrames: 38, isHighlight: true },
        { text: "A 770-BILLION", fromFrame: 38, durationInFrames: 38, isHighlight: true },
        { text: "PARAMETER", fromFrame: 76, durationInFrames: 38, isHighlight: false },
        { text: "OPEN-WEIGHTS MONSTER.", fromFrame: 114, durationInFrames: 37, isHighlight: true },
      ],
    },
    {
      id: "scene-3",
      type: "editorial-card",
      tabLabel: "capacity",
      tabColor: "#06B6D4",
      title: "1,000,000 Context",
      subtitle: "Massive Repository & Codebase Ingestion",
      durationInFrames: 136,
      items: [
        { num: "1", title: "Full Repo Buffer", desc: "Scan 500+ files and dependencies with zero degradation", tag: "100x ★", tagColor: "#CCFBF1" },
        { num: "2", title: "Needle in Haystack", desc: "100% retrieval accuracy at 1 million tokens", tag: "verified", tagColor: "#DCFCE7" },
        { num: "3", title: "Zero Hallucination", desc: "Architectural precision across large document bases", tag: "official", tagColor: "#FEF9C3" },
        { num: "4", title: "Fast Retrieval", desc: "Instant lookups without fine-tuning latency", tag: "partner", tagColor: "#E0E7FF" },
      ],
      footerNote: "One short command runs across your entire codebase.",
      emote: "sparkle",
      captions: [
        { text: "IT PACKS A", fromFrame: 0, durationInFrames: 34, isHighlight: false },
        { text: "ONE MILLION", fromFrame: 34, durationInFrames: 34, isHighlight: true },
        { text: "TOKEN CONTEXT", fromFrame: 68, durationInFrames: 34, isHighlight: true },
        { text: "WINDOW FOR REPOS.", fromFrame: 102, durationInFrames: 34, isHighlight: true },
      ],
    },
    {
      id: "scene-4",
      type: "editorial-card",
      tabLabel: "workflows",
      tabColor: "#EC4899",
      title: "3D & Dev Studio",
      subtitle: "Direct Unreal Engine 5 & Full-Stack Coding",
      durationInFrames: 126,
      items: [
        { num: "1", title: "Software Engineering", desc: "End-to-end bug fixing, refactoring, and code reviews", tag: "Dev Agent", tagColor: "#DCFCE7" },
        { num: "2", title: "3D Mesh Gen", desc: "Auto-generates procedural 3D environments from text", tag: "UE5 Ready", tagColor: "#FCE7F3" },
        { num: "3", title: "Asset Pipeline", desc: "Direct export to GLTF, FBX, and Unreal Engine projects", tag: "partner", tagColor: "#FEF9C3" },
        { num: "4", title: "Zero Bottleneck", desc: "Single prompt to working interactive demo", tag: "10x Speed", tagColor: "#E0E7FF" },
      ],
      footerNote: "Handling everything from software engineering to 3D game dev!",
      emote: "sparkle",
      captions: [
        { text: "HANDLING EVERYTHING", fromFrame: 0, durationInFrames: 31, isHighlight: false },
        { text: "FROM SOFTWARE", fromFrame: 31, durationInFrames: 31, isHighlight: true },
        { text: "ENGINEERING TO", fromFrame: 62, durationInFrames: 31, isHighlight: false },
        { text: "3D GAME DEV!", fromFrame: 93, durationInFrames: 33, isHighlight: true },
      ],
    },
    {
      id: "scene-5",
      type: "editorial-card",
      tabLabel: "open source",
      tabColor: "#F59E0B",
      title: "Hugging Face Hub",
      subtitle: "Zero API Paywalls • 100% Free Weights",
      durationInFrames: 155,
      items: [
        { num: "1", title: "Zero API Paywall", desc: "Download base model & fine-tune on your own GPUs", tag: "100% Free", tagColor: "#DCFCE7" },
        { num: "2", title: "Safetensors", desc: "Full fp16 and 4-bit quantized formats ready to run", tag: "official", tagColor: "#FEF9C3" },
        { num: "3", title: "Ollama & vLLM", desc: "Community inference support available on day 1", tag: "open", tagColor: "#E0E7FF" },
        { num: "4", title: "Commercial Use", desc: "Permissive license for building and selling AI tools", tag: "verified", tagColor: "#FCE7F3" },
      ],
      footerNote: "While closed models charge, HY4 is 100% free!",
      emote: "trophy",
      captions: [
        { text: "WHILE CLOSED", fromFrame: 0, durationInFrames: 38, isHighlight: false },
        { text: "MODELS CHARGE,", fromFrame: 38, durationInFrames: 39, isHighlight: true },
        { text: "HY4 IS", fromFrame: 77, durationInFrames: 39, isHighlight: false },
        { text: "100% FREE!", fromFrame: 116, durationInFrames: 39, isHighlight: true },
      ],
    },
    {
      id: "scene-6",
      type: "cta-card",
      tabLabel: "get setup",
      tabColor: "#10B981",
      title: "Bytes with Bittu ⚡",
      subtitle: "Daily AI Engineering Alpha & Open-Source Tools",
      durationInFrames: 119,
      items: [
        { num: "1", title: "Full Setup Guide", desc: "Step-by-step local install instructions with scripts", tag: "official", tagColor: "#DCFCE7" },
        { num: "2", title: "Model Weights", desc: "Direct links and quantization configs on GitHub", tag: "free", tagColor: "#FEF9C3" },
        { num: "3", title: "Daily Alpha", desc: "Never miss a major AI release or architecture breakdown", tag: "daily", tagColor: "#E0E7FF" },
      ],
      footerNote: "Comment 'INSTALL' for the full setup guide & alpha!",
      emote: "trophy",
      captions: [
        { text: "COMMENT INSTALL", fromFrame: 0, durationInFrames: 30, isHighlight: true },
        { text: "FOR THE", fromFrame: 30, durationInFrames: 30, isHighlight: false },
        { text: "FULL SETUP", fromFrame: 60, durationInFrames: 30, isHighlight: true },
        { text: "GUIDE & ALPHA!", fromFrame: 90, durationInFrames: 29, isHighlight: true },
      ],
    },
  ],
};
